name: Go
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      GO_ENV: test
    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Get dependencies
        run: go mod tidy

      - name: Test
        run: go test ./...
