name: goreleaser

on:
  push:
    tags:
      - '*'
jobs:
    goreleaser:
        if: github.repository == 'hantbk/vtsbackup'
        runs-on: ubuntu-latest
        steps:
        - name: Checkout
          uses: actions/checkout@v2
          with:
              fetch-depth: 0
        - name: Setup Go
          uses: actions/setup-go@v4
          with:
            go-version: 1.23
        - name: Install GoReleaser
          uses: goreleaser/goreleaser-action@v4
          with:
            version: latest
            args: release --rm-dist
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}