name: Build & Test
on:
  pull_request:
  push:
    branches:
      - "*"
    tags:
      - "*"
jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    env:
      GO_ENV: test
      GOPATH: ${{ github.workspace }}/go
    steps:
      - name: Skip Duplicate Actions
        uses: fkirc/skip-duplicate-actions@v5.3.0

      - uses: actions/checkout@v3
      
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20
        id: go
        
      - name: "Build Web"
        run: |
          cd web
          yarn && yarn build

      - name: Get dependencies
        run: go get -v -t -d ./...
        shell: /usr/bin/bash -e {0}
        env:
          GO_ENV: test
          GOPATH: ${{ github.workspace }}/go
          
      - name: Test
        run: go test ./...
